version: "3"
services:
  api:
    image: "martstech/dwallet-api"
    mem_limit: 128m
    hostname: api
    environment:
      - MYSQL_USER=$MYSQL_USER
      - MYSQL_PASSWORD=$MYSQL_PASSWORD
      - MYSQL_HOST=$MYSQL_HOST
      - MYSQL_PORT=$MYSQL_PORT
      - MYSQL_DATABASE=$MYSQL_DATABASE
      - JWTSettings:TokenKey=$JWT_SECRET
  proxy:
    image: "martstech/dwallet-proxy"
    mem_limit: 128m
    hostname: proxy
    ports:
      - "80:80"
